spring.application.name=demo

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

<<<<<<< HEAD
server.port=8080
=======
server.port=8080
>>>>>>> c7b204a67831484fb15f7935fee88a654ad4e418
